sudo: required

# PREPARE ENVIRONMENT
#-------------------------------------------------------------------------------

services:
  - docker

install:
  - echo "TODO - install dependencies (specific version of docker?)"

# RUN HEALTHCHECK TEST
#-------------------------------------------------------------------------------

# Bring up the application
before_script:
  - docker-compose up --build -d

# Run the test script
script:
  - ./scripts/test.sh

# Bring down the application
after_script:
  - docker-compose down
  - ./scripts/push_docker.sh

deploy:
  - ./scripts/deploy.sh
