sudo: required

# PREPARE ENVIRONMENT
#-------------------------------------------------------------------------------

services:
  - docker

install:
  - echo "TODO - install dependencies (specific version of docker?)"

# RUN HEALTHCHECK TEST
#-------------------------------------------------------------------------------

# Bring up the application
before_script:
  - docker-compose up --build -d

# Run the test script
script:
  - ./test/test.sh

# Bring down the application
after_script:
  - docker-compose down
  - echo "Uploading to Dockerhub..."

  # require the branch name to be master
  - if [ $TRAVIS_BRANCH == "master" ]; then
      echo "master"
    else
      echo "not master"
    fi

# DEPLOY TO SERVER
#-------------------------------------------------------------------------------

# If the build succeeds...
after_success:
  - echo "It finally worked! :)"


# If the build fails
after_failure:
  - echo "It failed :()"
