sudo: required

services:
  - docker

install:
  - echo "TODO - install dependencies (specific version of docker?)"

before_script:
  - docker-compose up --build -d

script:
  - ./scripts/test.sh
  - docker-compose down
  - ./scripts/push_docker.sh
