sudo: required

# language: node_js

services:
  - docker

install:
  - echo "installing"

before_script:
  - docker-compose up --build -d

script:
  - ./test/test.sh

after_script:
  - docker-compose down
